### ISSUE TITLE
Run some commands inside VM

### ISSUE THREAD

**Issue by rivaros** [justincormack/nsenter1#3]
Hi Justin,

As the author of nsenter1 you are the only person probably who can help me with small issue:

Before starting our containers we want to run 2 commands inside VM host

‘’’
modprobe nfs
modprobe nfsd
‘’’

Could this be dine easily with ncenter1?

**Comment by justincormack** [comment]
yes you should be able to do `docker run --pid=host --privileged justincormack/nsenter1 /sbin/modprobe nfsd` in principal

**Comment by justincormack** [comment]
It connects to the host in all cases.
