### ISSUE TITLE
After ssh, Is there a way to create directory or file?

### ISSUE THREAD

**Issue by suchitgupta01** [justincormack/nsenter1#8]
I ssh using `docker run -it --rm --privileged --pid=host justincormack/nsenter1`.

Now, I am trying to create a directory or a file and I am getting "Read-only file system"

```
/mnt # sudo mkdir data
/bin/sh: sudo: not found
/mnt # mkdir data
mkdir: can't create directory 'data': Read-only file system
/mnt # sh -c "echo 'Hello from Kubernetes storage' > /mnt/index.html"
sh: can't create /mnt/index.html: Read-only file system

```

Is there a workaround? 

I am trying below:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

and want to see how files get's stored.

**Comment by justincormack** [comment]
The host you are logging into has a read only filesystem, unfortunately this tool cannot change that. You might be able to remount the filesystem rw.
