### ISSUE TITLE
Changes to ip addresses are not saved

### ISSUE THREAD

**Issue by christmasjumper** [justincormack/nsenter1#9]
Hi,

I'm using this to add ip addresses exposed in the host OS (MacOS) so that I can map containers straight to the IP address.

This works until I restart docker and then the changes seem to be lost - am I missing something?

**Comment by justincormack** [comment]
Hi, Docker for Mac and Windows run ephemeral VMs that do not save their state, they are designed to reboot to a known state, so there is nothing you can do here.
